2018-10-21 15:11:15,864 INFO: Microblog startup [in /Users/max/Documents/Python/microblog/app/__init__.py:66]
2018-10-21 15:12:14,748 INFO: Microblog startup [in /Users/max/Documents/Python/microblog/app/__init__.py:66]
2018-10-21 15:35:00,024 INFO: Microblog startup [in /Users/max/Documents/Python/microblog/app/__init__.py:66]
2018-10-21 15:35:57,886 INFO: Microblog startup [in /Users/max/Documents/Python/microblog/app/__init__.py:66]
2018-10-21 15:37:28,704 INFO: Microblog startup [in /Users/max/Documents/Python/microblog/app/__init__.py:66]
2018-10-21 15:39:14,996 INFO: Microblog startup [in /Users/max/Documents/Python/microblog/app/__init__.py:66]
2018-10-21 15:39:21,704 ERROR: Exception on /translate [POST] [in /Users/max/Documents/Python/microblog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/max/Documents/Python/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/max/Documents/Python/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/max/Documents/Python/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/max/Documents/Python/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/max/Documents/Python/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/max/Documents/Python/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/max/Documents/Python/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/max/Documents/Python/microblog/app/routes.py", line 214, in translate_text
    request.form['dest_language'])})
  File "/Users/max/Documents/Python/microblog/app/translate.py", line 14, in translate
    text_wrap = '[{"Text": "' + text.encode('utf-8') + '"}]'
TypeError: must be str, not bytes
2018-10-21 15:41:17,076 INFO: Microblog startup [in /Users/max/Documents/Python/microblog/app/__init__.py:66]
2018-10-21 15:41:26,346 ERROR: Exception on /translate [POST] [in /Users/max/Documents/Python/microblog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/max/Documents/Python/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/max/Documents/Python/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/max/Documents/Python/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/max/Documents/Python/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/max/Documents/Python/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/max/Documents/Python/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/max/Documents/Python/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/max/Documents/Python/microblog/app/routes.py", line 214, in translate_text
    request.form['dest_language'])})
  File "/Users/max/Documents/Python/microblog/app/translate.py", line 14, in translate
    text_wrap = '[{"Text": "' + text.decode('utf-8') + '"}]'
AttributeError: 'str' object has no attribute 'decode'
2018-10-21 15:43:47,708 INFO: Microblog startup [in /Users/max/Documents/Python/microblog/app/__init__.py:66]
2018-10-21 15:44:05,923 ERROR: Exception on /translate [POST] [in /Users/max/Documents/Python/microblog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/max/Documents/Python/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/max/Documents/Python/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/max/Documents/Python/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/max/Documents/Python/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/max/Documents/Python/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/max/Documents/Python/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/max/Documents/Python/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/max/Documents/Python/microblog/app/routes.py", line 214, in translate_text
    request.form['dest_language'])})
  File "/Users/max/Documents/Python/microblog/app/translate.py", line 14, in translate
    text_wrap = "[{'Text': '{}'}]".format(text)
KeyError: "'Text'"
2018-10-21 15:46:11,430 INFO: Microblog startup [in /Users/max/Documents/Python/microblog/app/__init__.py:66]
2018-10-21 15:47:23,150 INFO: Microblog startup [in /Users/max/Documents/Python/microblog/app/__init__.py:66]
2018-10-21 15:48:30,436 INFO: Microblog startup [in /Users/max/Documents/Python/microblog/app/__init__.py:66]
2018-10-21 15:53:16,212 INFO: Microblog startup [in /Users/max/Documents/Python/microblog/app/__init__.py:66]
2018-10-21 21:58:39,389 INFO: Microblog startup [in /Users/max/Documents/Python/microblog/app/__init__.py:66]
2018-10-21 22:29:40,809 INFO: Microblog startup [in /Users/max/Documents/Python/microblog/app/__init__.py:66]
2018-10-21 22:35:31,636 INFO: Microblog startup [in /Users/max/Documents/Python/microblog/app/__init__.py:66]
2018-10-22 22:39:36,575 INFO: Microblog startup [in /Users/max/Documents/Python/microblog/app/__init__.py:66]
